# Generated by Django 4.2.16 on 2024-09-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_film_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='kinopoisk_dev_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID от KinopoiskAPI'),
        ),
        migrations.AddField(
            model_name='film',
            name='movie_length',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Длительность'),
        ),
    ]
