# Generated by Django 4.2.16 on 2024-09-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_film_kinopoisk_dev_id_film_movie_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.URLField(default=None, max_length=500, null=True, verbose_name='Ссылка на постер'),
        ),
    ]
